Create the class spells list index directory if it doesn't exist before trying to write to it with the index builder
Fixes this error when running `python ./build_indexes.py` for the first time (as instructed in README.md):
IOError: [Errno 2] No such file or directory: './docs/spellcasting/spell_lists/bard_spells.md'